# Generated by Django 6.0.7 on 2026-07-18 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority_class', models.IntegerField(choices=[(4, 'Critical'), (3, 'High'), (2, 'Normal'), (1, 'Backburner')], default=2)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget_staff_days', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending approval'), ('done', 'Done'), ('shelved', 'Shelved')], default='active', max_length=20)),
                ('sponsor_notes', models.TextField(blank=True)),
                ('out_of_scope', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('nominal_hours_per_day', models.FloatField(default=8.0)),
                ('focus_factor', models.FloatField(default=0.75)),
                ('is_manager', models.BooleanField(default=False)),
                ('calendar_shared', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('probability', models.IntegerField(default=3)),
                ('impact', models.IntegerField(default=3)),
                ('trigger_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('mitigation', models.TextField(blank=True)),
                ('open', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('blocked', 'blocked'), ('waiting-external', 'waiting-external'), ('done', 'done')], default='todo', max_length=20)),
                ('est_optimistic', models.FloatField(blank=True, null=True)),
                ('est_likely', models.FloatField(blank=True, null=True)),
                ('est_pessimistic', models.FloatField(blank=True, null=True)),
                ('actual_hours', models.FloatField(default=0.0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('delay_profile', models.CharField(choices=[('cliff', 'cliff'), ('linear', 'linear'), ('slow_burn', 'slow_burn')], default='linear', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='comma-separated', max_length=200)),
                ('done_definition', models.TextField(blank=True)),
                ('blocked_by', models.CharField(blank=True, max_length=200)),
                ('blocked_since', models.DateField(blank=True, null=True)),
                ('reopened_count', models.IntegerField(default=0)),
                ('last_touched', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='dependents', to='core.task')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('velocity_actual', models.FloatField(blank=True, null=True)),
                ('retro_note', models.TextField(blank=True)),
                ('committed', models.ManyToManyField(blank=True, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.FloatField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='core.task')),
            ],
        ),
    ]
