# Generated by Django 6.0.6 on 2026-07-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.FloatField(default=4.0)),
                ('priority', models.FloatField(default=2.0)),
                ('criticality', models.FloatField(default=1.5)),
                ('staleness', models.FloatField(default=0.5)),
                ('unblock', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name_plural': 'scoring settings',
            },
        ),
    ]
