# Generated by Django 6.0.6 on 2026-07-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scoringsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recur_every_days',
            field=models.IntegerField(blank=True, help_text='Days until the next occurrence. Leave blank for a one-off task. On completion, the next instance is created automatically.', null=True),
        ),
    ]
