# Generated by Django 6.0.6 on 2026-07-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_recur_every_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('graph', 'Microsoft Outlook'), ('google', 'Google Calendar')], max_length=10)),
                ('source_id', models.CharField(max_length=300)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('busy_status', models.CharField(choices=[('free', 'free'), ('tentative', 'tentative'), ('busy', 'busy'), ('oof', 'oof')], default='busy', max_length=10)),
                ('all_day', models.BooleanField(default=False)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.staff')),
            ],
            options={
                'ordering': ['start'],
                'indexes': [models.Index(fields=['staff', 'start', 'end'], name='core_calend_staff_i_00c0c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'provider', 'source_id'), name='uniq_calendar_event_source')],
            },
        ),
    ]
