# Generated by Django 6.0.6 on 2026-07-21 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushedCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('graph', 'Microsoft Outlook'), ('google', 'Google Calendar')], max_length=10)),
                ('source_id', models.CharField(max_length=300)),
                ('pushed_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pushed_events', to='core.milestone')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pushed_focus_block', to='core.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('milestone__isnull', False)), fields=('provider', 'milestone'), name='uniq_pushed_milestone'), models.UniqueConstraint(condition=models.Q(('task__isnull', False)), fields=('provider', 'task'), name='uniq_pushed_focus_block')],
            },
        ),
    ]
