"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Where user-writable files (the database, a generated .env) live. Normally
# the same as BASE_DIR -- but when frozen into a standalone .exe
# (PyInstaller), BASE_DIR resolves inside a temp extraction folder that's
# wiped on every launch, so writable data has to live next to the .exe
# itself instead, or a user's portfolio would vanish every time they
# reopened the app. sys.frozen is set by PyInstaller; every non-packaged
# run (plain `manage.py`, Docker, the setup scripts) is unaffected.
if getattr(sys, "frozen", False):
    DATA_DIR = Path(sys.executable).resolve().parent
else:
    DATA_DIR = BASE_DIR

# Minimal stdlib .env loader — no python-dotenv dependency, matching the
# project's dependency-light rule. Reads KEY=VALUE lines from a .env file
# next to manage.py (or next to the .exe, when packaged) if one exists (see
# .env.example); real environment variables set another way always take
# precedence (setdefault).
_env_file = DATA_DIR / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith("#") or "=" not in _line:
            continue
        _key, _, _value = _line.partition("=")
        os.environ.setdefault(_key.strip(), _value.strip())


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Set
# DJANGO_SECRET_KEY (env var or .env) before running this anywhere but your
# own machine — see .env.example. The fallback below is fine for local dev
# only.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-me-before-any-real-deployment")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# CSRF trusted origins -- needed whenever the browser's Origin differs from
# Django's own idea of its host, e.g. behind an HTTPS reverse-proxy/tunnel
# (Codespaces, ngrok, a real deployment behind nginx). Self-hosters behind
# their own proxy set DJANGO_CSRF_TRUSTED_ORIGINS; Codespaces is
# auto-detected below since it's a supported zero-config path (see
# .devcontainer/) and CODESPACES is an env var GitHub itself sets, not
# something a random deployment could spoof into gaining trusted-origin
# status.
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

if os.environ.get("CODESPACES") == "true":
    _codespace_name = os.environ.get("CODESPACE_NAME", "")
    _forwarding_domain = os.environ.get("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN", "app.github.dev")
    if _codespace_name:
        _forwarded_host = "%s-8000.%s" % (_codespace_name, _forwarding_domain)
        ALLOWED_HOSTS.append(_forwarded_host)
        CSRF_TRUSTED_ORIGINS.append("https://%s" % _forwarded_host)
    # VS Code's embedded Simple Browser can present the forwarded port's
    # origin/host as plain localhost rather than the public forwarding URL
    # -- trust that too, only inside an actual Codespace.
    ALLOWED_HOSTS.append("localhost")
    CSRF_TRUSTED_ORIGINS.append("https://localhost:8000")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.mascot_mood',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Calendar-sync's workday-hours math (engine/calendar_capacity.py) runs
# against local wall-clock time -- self-hosters outside UTC should set
# DJANGO_TIME_ZONE to their own IANA zone (e.g. "America/Denver") in .env,
# or a synced meeting at 9am local will be measured against 9am UTC instead.
TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True


# --- Calendar OAuth (read-only sync, plan §7c) --------------------------
# Baked-in values are True Ascent Labs LLC's own shared OAuth app
# registrations, so "Connect Outlook"/"Connect Google" works out of the box
# for every downloader with one click -- self-hosters running their own
# Azure/Google registration override these the same way DJANGO_SECRET_KEY
# is overridden above. An empty client ID means "not configured" everywhere
# it's checked (Settings page, connect views, sync_calendar, desktop_app.py's
# background loop) -- never a crash, never a broken empty-client_id redirect.
MICROSOFT_GRAPH_CLIENT_ID = os.environ.get("JIMOTHY_GRAPH_CLIENT_ID", "")
MICROSOFT_GRAPH_AUTHORITY = os.environ.get(
    "JIMOTHY_GRAPH_AUTHORITY", "https://login.microsoftonline.com/common")
MICROSOFT_GRAPH_REDIRECT_URI = os.environ.get(
    "JIMOTHY_GRAPH_REDIRECT_URI", "http://localhost:8000/calendar/oauth/graph/callback/")

GOOGLE_CALENDAR_CLIENT_ID = os.environ.get("JIMOTHY_GOOGLE_CLIENT_ID", "")
GOOGLE_CALENDAR_CLIENT_SECRET = os.environ.get("JIMOTHY_GOOGLE_CLIENT_SECRET", "")
GOOGLE_CALENDAR_REDIRECT_URI = os.environ.get(
    "JIMOTHY_GOOGLE_REDIRECT_URI", "http://localhost:8000/calendar/oauth/google/callback/")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
